version : '3.8'

services:
  update-receiver:
    build: ./update-server
    ports: 
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis
    ports:
      - 6000:6379
  receiver-footbal:
    build: 
      context: ./simple-update-receiver
      args:
        - TOPIC=football
    ports:
      - "3001:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  receiver-goal:
    build: 
      context: ./simple-update-receiver
      args:
        - TOPIC=goal
    ports:
      - "3002:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  